# REDIS (RedisProperties)
# Redis数据库索引（默认为0）
spring.redis.database: 6
# Redis服务器地址
spring.redis.host: 10.143.117.25
#spring.redis.sentinel.nodes: 10.143.117.25:26379,10.143.117.25:26380,10.143.117.25:26381
#spring.redis.sentinel.master: meijiesit
# Redis服务器连接端口
spring.redis.port: 6379
# Redis服务器连接密码（默认为空）
spring.redis.password: OWMyOTVmOTJhNzd
# 连接池最大连接数（使用负值表示没有限制）
spring.redis.pool.max-active: 8
# 连接池最大阻塞等待时间（使用负值表示没有限制）
spring.redis.pool.max-wait: -1
# 连接池中的最大空闲连接
spring.redis.pool.max-idle: 8
# 连接池中的最小空闲连接
spring.redis.pool.min-idle: 0
# 连接超时时间（毫秒）
spring.redis.timeout: 0

# 如果有多个包名前缀，用逗号隔开
#fastjson.parser.autoTypeAccept: com.huang.