server:
  port: 8091

server.context-path: /mj

# Dubbo 服务消费者配置
spring:
  dubbo:
    application:
      name: web-api
    registry:
      address: zookeeper://localhost:2291
    scan: com.huang
  rabbitmq:
    addresses: localhost:5672
    virtual-host: sit
    publisher-confirms: true
    password: admin
    username: admin
    listener:
      acknowledge-mode: manual




spring.dubbo.application.owner: meijie-thirdparty-consumer
spring.dubbo.application.name: meijie-thirdparty-consumer
spring.dubbo.application.organization: gomefinance-meijie
spring.dubbo.registries[0].id: myfRegistry
spring.dubbo.registries[0].address: zookeeper://localhost:2291

rabbitmq.exchange.exception: exception_exchange
rabbitmq.queue.exception: exception_queue
rabbitmq.pushkey.exception: exception_pushkey

rabbitmq.queue.exception1: exception_queue1
rabbitmq.pushkey.exception1: exception_pushkey1

rabbitmq.queue.deadLetter: dealLetter_queue