package com.xu.drools;
import com.xu.drools.bean.Person;
import java.lang.Boolean;

rule "2"
    no-loop true
    activation-group "foo"
    salience 2
	when
        $p : Person(age > 30);
    then
		System.out.println("hello, young xu2!");
		$p.setName("xiaoming");

//		$p.setAge(51);
//		update($p);
end

rule "3"
    lock-on-active true
    activation-group "foo"
    salience 1
	when
        $p : Person(age > 30);
    then
		System.out.println("hello, young xu1!  ---------");
end


query "people2"
    person : Person( age > 30 )
end